import {Country} from "../models/Country";

const countriesFlags: Country[] = [
    { value: "AE", label: "UAE", phone: "971", flag: "https://flagcdn.com/w40/ae.png" },
    { value: "US", label: "USA", phone: "1", flag: "https://flagcdn.com/w40/us.png" },
    { value: "GB", label: "UK", phone: "44", flag: "https://flagcdn.com/w40/gb.png" },
    { value: "FR", label: "France", phone: "33", flag: "https://flagcdn.com/w40/fr.png" },
    { value: "DE", label: "Germany", phone: "49", flag: "https://flagcdn.com/w40/de.png" },
    { value: "AF", label: "Afghanistan", phone: "93", flag: "https://flagcdn.com/w40/af.png" },
    { value: "AX", label: "Åland Islands", phone: "358", flag: "https://flagcdn.com/w40/ax.png" },
    { value: "AL", label: "Albania", phone: "355", flag: "https://flagcdn.com/w40/al.png" },
    { value: "DZ", label: "Algeria", phone: "213", flag: "https://flagcdn.com/w40/dz.png" },
    { value: "AS", label: "American Samoa", phone: "1-684", flag: "https://flagcdn.com/w40/as.png" },
    { value: "AD", label: "Andorra", phone: "376", flag: "https://flagcdn.com/w40/ad.png" },
    { value: "AO", label: "Angola", phone: "244", flag: "https://flagcdn.com/w40/ao.png" },
    { value: "AI", label: "Anguilla", phone: "1-264", flag: "https://flagcdn.com/w40/ai.png" },
    { value: "AQ", label: "Antarctica", phone: "672", flag: "https://flagcdn.com/w40/aq.png" },
    { value: "AG", label: "Antigua and Barbuda", phone: "1-268", flag: "https://flagcdn.com/w40/ag.png" },
    { value: "AR", label: "Argentina", phone: "54", flag: "https://flagcdn.com/w40/ar.png" },
    { value: "AM", label: "Armenia", phone: "374", flag: "https://flagcdn.com/w40/am.png" },
    { value: "AW", label: "Aruba", phone: "297", flag: "https://flagcdn.com/w40/aw.png" },
    { value: "AU", label: "Australia", phone: "61", flag: "https://flagcdn.com/w40/au.png" },
    { value: "AT", label: "Austria", phone: "43", flag: "https://flagcdn.com/w40/at.png" },
    { value: "AZ", label: "Azerbaijan", phone: "994", flag: "https://flagcdn.com/w40/az.png" },
    { value: "BS", label: "Bahamas", phone: "1-242", flag: "https://flagcdn.com/w40/bs.png" },
    { value: "BH", label: "Bahrain", phone: "973", flag: "https://flagcdn.com/w40/bh.png" },
    { value: "BD", label: "Bangladesh", phone: "880", flag: "https://flagcdn.com/w40/bd.png" },
    { value: "BB", label: "Barbados", phone: "1-246", flag: "https://flagcdn.com/w40/bb.png" },
    { value: "BY", label: "Belarus", phone: "375", flag: "https://flagcdn.com/w40/by.png" },
    { value: "BE", label: "Belgium", phone: "32", flag: "https://flagcdn.com/w40/be.png" },
    { value: "BZ", label: "Belize", phone: "501", flag: "https://flagcdn.com/w40/bz.png" },
    { value: "BJ", label: "Benin", phone: "229", flag: "https://flagcdn.com/w40/bj.png" },
    { value: "BM", label: "Bermuda", phone: "1-441", flag: "https://flagcdn.com/w40/bm.png" },
    { value: "BT", label: "Bhutan", phone: "975", flag: "https://flagcdn.com/w40/bt.png" },
    { value: "BO", label: "Bolivia", phone: "591", flag: "https://flagcdn.com/w40/bo.png" },
    { value: "BQ", label: "Bonaire, Sint Eustatius and Saba", phone: "599", flag: "https://flagcdn.com/w40/bq.png" },
    { value: "BA", label: "Bosnia and Herzegovina", phone: "387", flag: "https://flagcdn.com/w40/ba.png" },
    { value: "BW", label: "Botswana", phone: "267", flag: "https://flagcdn.com/w40/bw.png" },
    { value: "BV", label: "Bouvet Island", phone: "", flag: "https://flagcdn.com/w40/bv.png" },
    { value: "BR", label: "Brazil", phone: "55", flag: "https://flagcdn.com/w40/br.png" },
    { value: "IO", label: "British Indian Ocean Territory", phone: "246", flag: "https://flagcdn.com/w40/io.png" },
    { value: "BN", label: "Brunei Darussalam", phone: "673", flag: "https://flagcdn.com/w40/bn.png" },
    { value: "BG", label: "Bulgaria", phone: "359", flag: "https://flagcdn.com/w40/bg.png" },
    { value: "BF", label: "Burkina Faso", phone: "226", flag: "https://flagcdn.com/w40/bf.png" },
    { value: "BI", label: "Burundi", phone: "257", flag: "https://flagcdn.com/w40/bi.png" },
    { value: "CV", label: "Cabo Verde", phone: "238", flag: "https://flagcdn.com/w40/cv.png" },
    { value: "KH", label: "Cambodia", phone: "855", flag: "https://flagcdn.com/w40/kh.png" },
    { value: "CM", label: "Cameroon", phone: "237", flag: "https://flagcdn.com/w40/cm.png" },
    { value: "CA", label: "Canada", phone: "1", flag: "https://flagcdn.com/w40/ca.png" },
    { value: "KY", label: "Cayman Islands", phone: "1-345", flag: "https://flagcdn.com/w40/ky.png" },
    { value: "CF", label: "Central African Republic", phone: "236", flag: "https://flagcdn.com/w40/cf.png" },
];

export default countriesFlags;
